name: Reusable workflow - Build latest image

on:
  workflow_call:
    inputs:
      repository_name:
        required: true
        type: string
      secrets:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ORG_PERSONAL_ACCESS_TOKEN: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN }}

jobs:
  push_to_registry:
    name: Build & upload to GitHub registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build and Push
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: zebrainy/${{ inputs.repository_name }}
          tags: latest

      # - name: Tag new version
      #   uses: pkgdeps/action-package-version-to-git-tag@v1.5.0
      #   with:
      #     github_token: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN }}
      #     github_repo: ${{ github.repository }}
      #     git_commit_sha: ${{ github.sha }}
      #     git_tag_prefix: "v"