name: Reusable workflow - Build branch WebView-bundle version

on:
  workflow_call:
    inputs:
      bundle_name:
        required: true
        type: string
      build_command:
        required: false
        type: string
        default: ci:build
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn ${{ inputs.build_command }}

        
      - name: Archive
        run: |
          pushd dist
          zip -r dist.zip *
          popd

      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1

      # Use branch name for whatever purpose
      - run: echo ${BRANCH_NAME}
        
      - name: Prepare S3 upload
        run: |
          mkdir -p s3/${BRANCH_NAME}
          mv dist/dist.zip s3/${BRANCH_NAME}/latest.zip
          mv dist s3/${BRANCH_NAME}/latest

      # - name: Upload to S3 AWS
      #   uses: Zebrainy/s3-sync-action@v2
      #   with:
      #     dirname: s3
      #     s3dirname: web-bundles/bundles/${{ inputs.bundle_name }}/branches
      #     bucketname: web-bundles
      #     REGION: us-east-2
      #     AWS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload to S3 SELECTEL
        uses: Zebrainy/s3-sync-action@s1
        with:
          dirname: s3
          s3dirname: web-bundles/bundles/${{ inputs.bundle_name }}/branches
          bucketname: web-bundles
          AWS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SELECTEL }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SELECTEL }} 

      - name: Print URLs
        run: |
          echo Selectel:
          # echo "https://d32vx8mc5b2105.cloudfront.net/web-bundles/bundles/${{ inputs.bundle_name }}/branches/${BRANCH_NAME}/latest/index.html"
          # echo "https://d32vx8mc5b2105.cloudfront.net/web-bundles/bundles/${{ inputs.bundle_name }}/branches/${BRANCH_NAME}/latest.zip"
          echo "https://6a39d29f-7919-4a2c-b54e-f8066f9effbb.selcdn.net/web-bundles/bundles/${{ inputs.bundle_name }}/branches/${BRANCH_NAME}/latest/index.html"
          echo "https://6a39d29f-7919-4a2c-b54e-f8066f9effbb.selcdn.net/web-bundles/bundles/${{ inputs.bundle_name }}/branches/${BRANCH_NAME}/latest.zip
