name: Reusable workflow - Build latest WebView-bundle

on:
  workflow_call:
    inputs:
      bundle_name:
        required: true
        type: string
      build_command:
        required: false
        type: string
        default: ci:build
      custom_tag:
        required: false
        type: string
        default: v
    secrets:
      ORG_PERSONAL_ACCESS_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  push_to_registry:
    name: Build WebView-bundle & upload latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn ${{ inputs.build_command }}

      - name: Archive
        run: |
          pushd dist
          zip -r dist.zip *
          popd

      - name: Prepare S3 upload
        run: |
          mkdir s3
          mv dist/dist.zip s3/latest.zip
          mv dist s3/latest

      - name: Upload to S3 AWS
        uses: Zebrainy/s3-sync-action@v2
        with:
          dirname: s3
          s3dirname: web-bundles/bundles/${{ inputs.bundle_name }}
          bucketname: web-bundles
          REGION: us-east-2
          AWS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload to S3 SELECTEL
        uses: Zebrainy/s3-sync-action@s1
        continue-on-error: true
        with:
          dirname: s3
          s3dirname: web-bundles/bundles/${{ inputs.bundle_name }}
          bucketname: web-bundles
          AWS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_SELECTEL }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_SELECTEL }}   

      - name: Print URLs
        run: |
          echo AWS:
          echo "https://d32vx8mc5b2105.cloudfront.net/web-bundles/bundles/${{ inputs.bundle_name }}/latest/index.html"
          echo "https://d32vx8mc5b2105.cloudfront.net/web-bundles/bundles/${{ inputs.bundle_name }}/latest.zip"
          
      - name: Tag new version (v1)
        uses: pkgdeps/action-package-version-to-git-tag@v1.5.0
        with:
          github_token: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "${{ inputs.custom_tag }}"