name: Reusable workflow - Build latest WebView-bundle

on:
  workflow_call:
    inputs:
      bundle_name:
        required: true
        type: string
      build_command:
        required: false
        type: string
        default: ci:build
    secrets:
      ORG_PERSONAL_ACCESS_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      squidex_client_secret:
        required: true

jobs:
  push_to_registry:
    name: Build WebView-bundle & upload latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
        
      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn ${{ inputs.build_command }}

      - name: Archive
        run: |
          pushd dist
          zip -r dist.zip *
          popd

      - name: Prepare S3 upload
        run: |
          mkdir s3
          mv dist/dist.zip s3/latest.zip
          mv dist s3/latest

      - name: Upload archive to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          SOURCE_DIR: 's3'
          DEST_DIR: 'web-bundles/bundles/${{ inputs.bundle_name }}'
          AWS_S3_BUCKET: web-bundles
          AWS_REGION: 'us-east-2'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Print URLs
        run: |
          echo AWS:
          echo "https://d32vx8mc5b2105.cloudfront.net/web-bundles/bundles/${{ inputs.bundle_name }}/latest/index.html"
          echo "https://d32vx8mc5b2105.cloudfront.net/web-bundles/bundles/${{ inputs.bundle_name }}/latest.zip"
          
      - name: Tag new version (v1)
        uses: pkgdeps/action-package-version-to-git-tag@v1.5.0
        with:
          github_token: ${{ secrets.ORG_PERSONAL_ACCESS_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"